

class ResGetContainerList {
  ResGetContainerList({
    this.success,
    this.message,
    this.data,
    this.statusCode,
    this.statusValueCode,
  });

  bool? success;
  String? message;
  List<ResGetContainerListData>? data;
  int? statusCode;
  int? statusValueCode;

  factory ResGetContainerList.fromJson(Map<String, dynamic> json) => ResGetContainerList(
    success: json["success"] == null ? null : json["success"],
    message: json["message"] == null ? null : json["message"],
    data: json["data"] == null ? null : List<ResGetContainerListData>.from(json["data"].map((x) => ResGetContainerListData.fromJson(x))),
    statusCode: json["statusCode"] == null ? null : json["statusCode"],
    statusValueCode: json["statusValueCode"] == null ? null : json["statusValueCode"],
  );

  Map<String, dynamic> toJson() => {
    "success": success == null ? null : success,
    "message": message == null ? null : message,
    "data": data == null ? null : List<dynamic>.from(data!.map((x) => x.toJson())),
    "statusCode": statusCode == null ? null : statusCode,
    "statusValueCode": statusValueCode == null ? null : statusValueCode,
  };
}

class ResGetContainerListData {
  ResGetContainerListData({
    this.containerId,
    this.containerCode,
    this.containerName,
    this.title,
    this.detail,
    this.companyId,
    this.airReceivingLocationId,
    this.warehouseId,
    this.receivingTypeTerm,
    this.dateOfShipment,
    this.eta,
    this.ata,
    this.conainerStatusTerm,
    this.unloadingProgress,
    this.trackingNo,
    this.uploadFileId,
    this.isActive,
    this.updatelog,
    this.shipperId,
    this.receivingLocationId,
    this.createdBy,
    this.createdOn,
    this.updatedBy,
    this.updatedOn,
    this.isManualEntry,
    this.manualEntry,
    this.isAbleToShowManualEntryyBtn,
    this.totalCount,
    this.rowNo,
    this.isEdit,
    this.containerPartCount,
    this.warehouseName,
    this.shipperName,
    this.airWarehouseId,
    this.airShipperId,
    this.airTrackingNo,
    this.airEta,
    this.airDateOfShipment,
    this.airDetail,
    this.airShipperName,
    this.etaDate,
    this.uploadContainerPartFile,
    this.isAutoGeneratedCode,
    this.autoGeneratedCode,
    this.receivingLocationName,
    this.airReceivingQtyId,
    this.containerPartsId,
    this.subTrackingNo,
    this.itemName,
    this.boxBarcode,
    this.partQty,
    this.monthYearDisplay,
    this.scanOnStr,
    this.statusTerm,
    this.receivedDate,
    this.completedDate,
    this.receivedDateStr,
    this.completedDateStr,
  });

  int? containerId;
  String? containerCode;
  String? containerName;
  String? title;
  dynamic? detail;
  int? companyId;
  int? airReceivingLocationId;
  int? warehouseId;
  String? receivingTypeTerm;
  DateTime? dateOfShipment;
  DateTime? eta;
  DateTime? ata;
  String? conainerStatusTerm;
  int? unloadingProgress;
  String? trackingNo;
  int? uploadFileId;
  bool? isActive;
  String? updatelog;
  int? shipperId;
  int? receivingLocationId;
  int? createdBy;
  DateTime? createdOn;
  int? updatedBy;
  DateTime? updatedOn;
  bool? isManualEntry;
  String? manualEntry;
  bool? isAbleToShowManualEntryyBtn;
  int? totalCount;
  int? rowNo;
  bool? isEdit;
  int? containerPartCount;
  String? warehouseName;
  dynamic? shipperName;
  int? airWarehouseId;
  int? airShipperId;
  dynamic? airTrackingNo;
  dynamic? airEta;
  dynamic? airDateOfShipment;
  dynamic? airDetail;
  dynamic? airShipperName;
  String? etaDate;
  dynamic? uploadContainerPartFile;
  bool? isAutoGeneratedCode;
  dynamic? autoGeneratedCode;
  dynamic? receivingLocationName;
  dynamic? airReceivingQtyId;
  dynamic? containerPartsId;
  dynamic? subTrackingNo;
  dynamic? itemName;
  dynamic? boxBarcode;
  dynamic? partQty;
  dynamic? monthYearDisplay;
  dynamic? scanOnStr;
  dynamic? statusTerm;
  DateTime? receivedDate;
  DateTime? completedDate;
  String? receivedDateStr;
  String? completedDateStr;

  factory ResGetContainerListData.fromJson(Map<String, dynamic> json) => ResGetContainerListData(
    containerId: json["containerID"] == null ? null : json["containerID"],
    containerCode: json["containerCode"] == null ? null : json["containerCode"],
    containerName: json["containerName"] == null ? null : json["containerName"],
    title: json["title"] == null ? null : json["title"],
    detail: json["detail"],
    companyId: json["companyID"] == null ? null : json["companyID"],
    airReceivingLocationId: json["airReceivingLocationID"] == null ? null : json["airReceivingLocationID"],
    warehouseId: json["warehouseID"] == null ? null : json["warehouseID"],
    receivingTypeTerm: json["receivingType_Term"] == null ? null : json["receivingType_Term"],
    dateOfShipment: json["dateOfShipment"] == null ? null : DateTime.parse(json["dateOfShipment"]),
    eta: json["eta"] == null ? null : DateTime.parse(json["eta"]),
    ata: json["ata"] == null ? null : DateTime.parse(json["ata"]),
    conainerStatusTerm: json["conainerStatus_Term"] == null ? null : json["conainerStatus_Term"],
    unloadingProgress: json["unloadingProgress"] == null ? null : json["unloadingProgress"],
    trackingNo: json["trackingNo"] == null ? null : json["trackingNo"],
    uploadFileId: json["uploadFileID"] == null ? null : json["uploadFileID"],
    isActive: json["isActive"] == null ? null : json["isActive"],
    updatelog: json["updatelog"] == null ? null : json["updatelog"],
    shipperId: json["shipperID"] == null ? null : json["shipperID"],
    receivingLocationId: json["receivingLocationID"] == null ? null : json["receivingLocationID"],
    createdBy: json["createdBy"] == null ? null : json["createdBy"],
    createdOn: json["createdOn"] == null ? null : DateTime.parse(json["createdOn"]),
    updatedBy: json["updatedBy"] == null ? null : json["updatedBy"],
    updatedOn: json["updatedOn"] == null ? null : DateTime.parse(json["updatedOn"]),
    isManualEntry: json["isManualEntry"] == null ? null : json["isManualEntry"],
    manualEntry: json["manualEntry"] == null ? null : json["manualEntry"],
    isAbleToShowManualEntryyBtn: json["isAbleToShowManualEntryyBTN"] == null ? null : json["isAbleToShowManualEntryyBTN"],
    totalCount: json["totalCount"] == null ? null : json["totalCount"],
    rowNo: json["rowNo"] == null ? null : json["rowNo"],
    isEdit: json["isEdit"] == null ? null : json["isEdit"],
    containerPartCount: json["containerPartCount"] == null ? null : json["containerPartCount"],
    warehouseName: json["warehouseName"] == null ? null : json["warehouseName"],
    shipperName: json["shipperName"],
    airWarehouseId: json["air_WarehouseID"] == null ? null : json["air_WarehouseID"],
    airShipperId: json["air_ShipperID"] == null ? null : json["air_ShipperID"],
    airTrackingNo: json["air_TrackingNo"],
    airEta: json["air_ETA"],
    airDateOfShipment: json["air_DateOfShipment"],
    airDetail: json["air_Detail"],
    airShipperName: json["air_ShipperName"],
    etaDate: json["etaDate"] == null ? null : json["etaDate"],
    uploadContainerPartFile: json["uploadContainerPartFile"],
    isAutoGeneratedCode: json["isAutoGeneratedCode"] == null ? null : json["isAutoGeneratedCode"],
    autoGeneratedCode: json["autoGeneratedCode"],
    receivingLocationName: json["receivingLocationName"],
    airReceivingQtyId: json["airReceivingQtyID"],
    containerPartsId: json["containerPartsID"],
    subTrackingNo: json["subTrackingNo"],
    itemName: json["itemName"],
    boxBarcode: json["boxBarcode"],
    partQty: json["partQty"],
    monthYearDisplay: json["monthYearDisplay"],
    scanOnStr: json["scanOnStr"],
    statusTerm: json["status_Term"],
    receivedDate: json["receivedDate"] == null ? null : DateTime.parse(json["receivedDate"]),
    completedDate: json["completedDate"],
    receivedDateStr: json["receivedDateStr"] == null ? null : json["receivedDateStr"],
    completedDateStr: json["completedDateStr"],
  );

  Map<String, dynamic> toJson() => {
    "containerID": containerId == null ? null : containerId,
    "containerCode": containerCode == null ? null : containerCode,
    "containerName": containerName == null ? null : containerName,
    "title": title == null ? null : title,
    "detail": detail,
    "companyID": companyId == null ? null : companyId,
    "airReceivingLocationID": airReceivingLocationId == null ? null : airReceivingLocationId,
    "warehouseID": warehouseId == null ? null : warehouseId,
    "receivingType_Term": receivingTypeTerm == null ? null : receivingTypeTerm,
    "dateOfShipment": dateOfShipment == null ? null : dateOfShipment!.toIso8601String(),
    "eta": eta == null ? null : eta!.toIso8601String(),
    "ata": ata == null ? null : ata!.toIso8601String(),
    "conainerStatus_Term": conainerStatusTerm == null ? null : conainerStatusTerm,
    "unloadingProgress": unloadingProgress == null ? null : unloadingProgress,
    "trackingNo": trackingNo == null ? null : trackingNo,
    "uploadFileID": uploadFileId == null ? null : uploadFileId,
    "isActive": isActive == null ? null : isActive,
    "updatelog": updatelog == null ? null : updatelog,
    "shipperID": shipperId == null ? null : shipperId,
    "receivingLocationID": receivingLocationId == null ? null : receivingLocationId,
    "createdBy": createdBy == null ? null : createdBy,
    "createdOn": createdOn == null ? null : createdOn!.toIso8601String(),
    "updatedBy": updatedBy == null ? null : updatedBy,
    "updatedOn": updatedOn == null ? null : updatedOn!.toIso8601String(),
    "isManualEntry": isManualEntry == null ? null : isManualEntry,
    "manualEntry": manualEntry == null ? null : manualEntry,
    "isAbleToShowManualEntryyBTN": isAbleToShowManualEntryyBtn == null ? null : isAbleToShowManualEntryyBtn,
    "totalCount": totalCount == null ? null : totalCount,
    "rowNo": rowNo == null ? null : rowNo,
    "isEdit": isEdit == null ? null : isEdit,
    "containerPartCount": containerPartCount == null ? null : containerPartCount,
    "warehouseName": warehouseName == null ? null : warehouseName,
    "shipperName": shipperName,
    "air_WarehouseID": airWarehouseId == null ? null : airWarehouseId,
    "air_ShipperID": airShipperId == null ? null : airShipperId,
    "air_TrackingNo": airTrackingNo,
    "air_ETA": airEta,
    "air_DateOfShipment": airDateOfShipment,
    "air_Detail": airDetail,
    "air_ShipperName": airShipperName,
    "etaDate": etaDate == null ? null : etaDate,
    "uploadContainerPartFile": uploadContainerPartFile,
    "isAutoGeneratedCode": isAutoGeneratedCode == null ? null : isAutoGeneratedCode,
    "autoGeneratedCode": autoGeneratedCode,
    "receivingLocationName": receivingLocationName,
    "airReceivingQtyID": airReceivingQtyId,
    "containerPartsID": containerPartsId,
    "subTrackingNo": subTrackingNo,
    "itemName": itemName,
    "boxBarcode": boxBarcode,
    "partQty": partQty,
    "monthYearDisplay": monthYearDisplay,
    "scanOnStr": scanOnStr,
    "status_Term": statusTerm,
    "receivedDate": receivedDate == null ? null : receivedDate!.toIso8601String(),
    "completedDate": completedDate,
    "receivedDateStr": receivedDateStr == null ? null : receivedDateStr,
    "completedDateStr": completedDateStr,
  };
}
